name: Build and Push to Nuget

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1

    - name: setup node
      uses: actions/setup-node@master
      with:
        node-version: '14'
 
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: build scripts
      run: |
        cd mjml-aspnetcore
        npm i
        npm run build

    - name: build 
      run: |
        dotnet build -c Release

    - name: pack
      run: |
        dotnet pack -c Release

    - name: publish
      run: |
        dotnet nuget push **/Mjml.AspNetCore*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate -k ${{ secrets.nuget }} --no-symbols 1 
